### ISSUE TITLE
Reconstruct pdb file error from MD.hdf5 file

### ISSUE THREAD

**Issue by HeJunhong1107** [sab148/MiSaTo-dataset#12]
when I tried to reconstruct pdb file in MD hdf5 file via data/processing/h5_to_pdb.py , there was some case failed because of the follow reason,  could you please help me out?

```
Generating pdb for MD dataset for 16PK frame 1
Traceback (most recent call last):
  File "data[/processing/h5_to_pdb.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a224d36227d.vscode-resource.vscode-cdn.net/processing/h5_to_pdb.py)", line 123, in <module>
    lines = create_pdb_lines_MD(trajectory_coordinates, atoms_type, atoms_number, atoms_residue, molecules_begin_atom_index, typeMap,residue_Map, nameMap)
  File "data[/processing/h5_to_pdb.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a224d36227d.vscode-resource.vscode-cdn.net/processing/h5_to_pdb.py)", line 76, in create_pdb_lines_MD
    atom_name = get_atom_name(i, atoms_number, residue_atom_index, residue_name, type_string, nameMap)
  File "data[/processing/h5_to_pdb.py](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a224d36227d.vscode-resource.vscode-cdn.net/processing/h5_to_pdb.py)", line 33, in get_atom_name
    atom_name = atomic_numbers_Map[atoms_number[i]]+str(residue_atom_index)
KeyError: 9

or 

Generating pdb for MD dataset for 1A3E frame 1
KeyError ('ILE', 20, 'N3')
KeyError ('ILE', 21, 'H')
KeyError ('ILE', 22, 'H')
KeyError ('ILE', 23, 'H')
KeyError ('ILE', 24, 'CX')
KeyError ('ILE', 25, 'HP')
KeyError ('ILE', 26, '3C')
KeyError ('ILE', 27, 'HC')
KeyError ('ILE', 28, 'CT')
KeyError ('ILE', 29, 'HC')
KeyError ('ILE', 30, 'HC')
KeyError ('ILE', 31, 'HC')
KeyError ('ILE', 32, '2C')
KeyError ('ILE', 33, 'HC')
KeyError ('ILE', 34, 'HC')
KeyError ('ILE', 35, 'CT')
KeyError ('ILE', 36, 'HC')
KeyError ('ILE', 37, 'HC')
KeyError ('ILE', 38, 'HC')
KeyError ('ILE', 39, 'C')
KeyError ('ILE', 40, 'O')

```

**Comment by t7morgen** [comment]
Thanks for your notice! 
I updated the atomic numbers map, so it should be fixed now for 16PK. 
The printed KeyError will also not appear anymore, the names of the atoms in 1A3E for this specific ILE residue is different than the atom names for other ILE residues, I hope this is not a problem. 
Quick notice: Frames numbering starts from 0 in case you want to convert the first frame.

**Comment by HeJunhong1107** [comment]
> d the atomic numbers map, so it s

thanks for the kind notice :)
